services:
  atlas-base:
    build:
      context: .
      dockerfile: Dockerfile.atlas-base
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - ATLAS_BASE_JAVA_VERSION=${ATLAS_BASE_JAVA_VERSION}
    image: atlas-base
    container_name: atlas-base
    networks:
      - atlas
    environment:
      - ATLAS_VERSION

networks:
  atlas:
    name: atlasnw
